### ISSUE TITLE
Two bugs when running all2all_async

### ISSUE THREAD

**Issue by ikarus-wing** [Funatiq/gossip#2]
Hi @Funatiq ,

I use the latest master (35d80ea1922ad04b30e16a17ac782087ffdb0e0c) to generate an async all2all plan and encounter the following errors:

```
user@scripts # python3 plan_from_topology_asynch.py all2all 0
main: 0 degree: 6 bisection width: 6.0
topology:
[[8. 1. 2. 1. 0. 0. 0. 2.]
 [1. 8. 1. 2. 0. 0. 2. 0.]
 [2. 1. 8. 2. 0. 1. 0. 0.]
 [1. 2. 2. 8. 1. 0. 0. 0.]
 [0. 0. 0. 1. 8. 2. 2. 1.]
 [0. 0. 1. 0. 2. 8. 1. 2.]
 [0. 2. 0. 0. 2. 1. 8. 1.]
 [2. 0. 0. 0. 1. 2. 1. 8.]]
max links: 2.0
plan_from_topology_asynch.py:108: RuntimeWarning: divide by zero encountered in true_divide
  lengths = np.where(capacities <= max_capacity, max_capacity / capacities, 1)
Traceback (most recent call last):
  File "plan_from_topology_asynch.py", line 131, in <module>
    parts_per_commodity = int(bisection_width // np.gcd(bisection_width, int(np.ceil(num_gpus/2)*np.floor(num_gpus/2))))
numpy.core._exceptions.UFuncTypeError: ufunc 'gcd' did not contain a loop with signature matching types (dtype('float64'), dtype('float64')) -> dtype('float64')
```

Using 997b7dbf6888ce48ee0d4f75d34b4c189c631eca will not have such errors and can generate a `all2all_plan.json`. But when I do `./execute all2all_async scripts/all2all_plan.json`, it seems the validation is not successful.

```
RUN: all2all_async
TIMING: 144.934 ms (malloc_devices)
TIMING: 15.1081 ms (zero_gpu_buffers)
INFO: 17179869184 bytes (all2all_async)
TIMING: 3.77651 ms (init_data)
TIMING: 56.6354 ms (multisplit)

Partition Table:
33553989 33562958 33552866 33555233 33552206 33551309 33550824 33556071
33550057 33558993 33556904 33553876 33551997 33558624 33554564 33550441
33550773 33565410 33548741 33556560 33555466 33547189 33554972 33556345
33551436 33553288 33558625 33564814 33555773 33550845 33549063 33551612
33562100 33553360 33559332 33548842 33548437 33555166 33557520 33550699
33552529 33559848 33550350 33552513 33551927 33552281 33556671 33559337
33566929 33547925 33548497 33554543 33548914 33557005 33554514 33557129
33552965 33555337 33563396 33547973 33550226 33554049 33559453 33552057

Required buffer sizes:
134215465 145385788 100656823 100669367 156594185 145392964 100665685 134216711 

TIMING: 345.666 ms (all2all_async)
ERROR on gpu 6 at index 190188512: 0 with predicate 0 
ERROR on gpu 6 at index 190188513: 0 with predicate 0 
ERROR on gpu 6 at index 190188514: 0 with predicate 0 
ERROR on gpu 6 at index 190188515: 0 with predicate 0 
ERROR on gpu 6 at index 190188516: 0 with predicate 0 
ERROR on gpu 6 at index 190188517: 0 with predicate 0 
ERROR on gpu 6 at index 190188518: 0 with predicate 0 
ERROR on gpu 6 at index 190188519: 0 with predicate 0 
ERROR on gpu 6 at index 190188520: 0 with predicate 0

...... (omitted due to a lot of lines)
```

--- 

Update:

I also tried the provided plan files such as `./execute all2all plans/dgx1_opt/all2all_plan.json`, but the validation still fails.

**Comment by Funatiq** [comment]
I fixed the type error. Unfortunately, I have no idea what's going wrong in the example. Are the errors always for GPU 6 only? Can you try to use `plans/dgx1_direct/all2all_plan.json` as this is the most simple plan?

**Comment by ikarus-wing** [comment]
Thank you for the fix, it solves the first bug. 

I tried `plans/dgx1_direct/all2all_plan.json` but it still failed. As far I can see from this [log.txt](https://github.com/Funatiq/gossip/files/4741631/log.txt) (this is not the entire log, I force stop the log printing due to too many lines), the errors happen on every GPU. I am using a machine with eight V100-GPUs (the topology is similar to DGX1).

Is there anything else I can try to debug?

**Comment by Funatiq** [comment]
Looking at the code, I suspect it is a sychronization error introduced in https://github.com/Funatiq/gossip/commit/89a111e580b2dcb5cce3f1bd18e38d9b18834032. Could you test the [new branch](https://github.com/Funatiq/gossip/tree/issue_2) please?

**Comment by ikarus-wing** [comment]
The new branch works, thank you! I will appreciate if it can be merged into master soon.

I notice that you fixed `multisplit.cu`. May I ask what exactly does `multisplit` do? I am confused by its name (and why we need it). From the code, I think it maintains a partition_table that records the length for communication on each GPU (please correct me if I am wrong).

**Comment by Funatiq** [comment]
I just merged the branch.

For the example code we use randomly generated numbers. Multisplit partitions the array of numbers according to a functor, which tells us which number should be transferred to which GPU (simple modulo in the example). The partition_table contains the length of the resulting partitions as you said.
This emulates a workflow for querying a distributed hash table across multiple GPUs.

If you just want to use gossip for communication you don't need the multisplit. You can just provide the send counts yourself.

**Comment by ikarus-wing** [comment]
I get it. Thank you very much. I will close this thread.
